"""Lesion-centric TorchIO patch sampler using offline fingerprint artifacts.

This sampler is intentionally much simpler than the previous adaptive grid-based
sampler. It does not rank dense grid candidates online. Instead, it consumes the
offline lesion catalog and sampling profile generated by ``fingerprint_refactored.py``
and samples patches directly around lesion centroids and lesion-conditioned roles.

Expected offline artifacts:
- ``lesion_catalog.jsonl``
- ``sampling_profile.json``

Important assumptions:
- Each subject corresponds to one side-specific VOI.
- Lesion coordinates in the catalog are VOI-local coordinates.
- Subjects passed from the dataloader must contain a stable ``catalog_key`` that
  matches ``lesion_catalog[*]['mask_path']``.
"""

from __future__ import annotations

import json
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, Iterator, List, Optional, Sequence, Tuple

import numpy as np
import torchio as tio

logger = logging.getLogger(__name__)

_DATACLASS_KWARGS = {"slots": True} if sys.version_info >= (3, 10) else {}

@dataclass(**_DATACLASS_KWARGS)
class LesionSamplerConfig:
    """Configuration for the simplified lesion-centric sampler."""

    tumor_label: int = 2
    background_sampling_prob: float = 0.0
    center_jitter_fraction: float = 0.10
    border_shift_fraction: float = 0.30
    context_shift_fraction: float = 0.55
    min_shift_voxels: float = 2.0
    max_patches_per_lesion: Optional[int] = None
    subject_key_name: str = "catalog_key"
    audit_enabled: bool = False


# Backward-compat alias for downstream imports that still expect the old name.
AdaptiveSamplerConfig = LesionSamplerConfig


def _ensure_min_size(subject: tio.Subject, patch_size: Tuple[int, int, int]) -> tio.Subject:
    """Pad a subject so a patch of ``patch_size`` can always be cropped."""
    spatial_shape = subject.spatial_shape
    padding_needed = [max(0, p - s) for p, s in zip(patch_size, spatial_shape)]

    if any(pad > 0 for pad in padding_needed):
        padding_tuple: Tuple[int, int, int, int, int, int] = (
            (padding_needed[0] + 1) // 2,
            padding_needed[0] // 2,
            (padding_needed[1] + 1) // 2,
            padding_needed[1] // 2,
            (padding_needed[2] + 1) // 2,
            padding_needed[2] // 2,
        )
        subject = tio.Pad(padding_tuple, padding_mode=-200)(subject)
        logger.debug("Padded subject from %s to %s", spatial_shape, subject.spatial_shape)

    return subject


def _load_jsonl(path: Path) -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line:
                rows.append(json.loads(line))
    return rows


def load_sampling_artifacts(
    lesion_catalog_path: str | Path,
    sampling_profile_path: str | Path,
) -> tuple[List[Dict[str, Any]], Dict[str, Any]]:
    """Load lesion catalog and sampling profile from disk."""
    lesion_catalog_path = Path(lesion_catalog_path)
    sampling_profile_path = Path(sampling_profile_path)

    if not lesion_catalog_path.exists():
        raise FileNotFoundError(f"Lesion catalog not found: {lesion_catalog_path}")
    if not sampling_profile_path.exists():
        raise FileNotFoundError(f"Sampling profile not found: {sampling_profile_path}")

    lesion_catalog = _load_jsonl(lesion_catalog_path)
    with sampling_profile_path.open("r", encoding="utf-8") as f:
        sampling_profile = json.load(f)

    return lesion_catalog, sampling_profile


def _group_lesions_by_catalog_key(lesion_catalog: Sequence[Dict[str, Any]]) -> Dict[str, List[Dict[str, Any]]]:
    grouped: Dict[str, List[Dict[str, Any]]] = {}
    for lesion in lesion_catalog:
        key = lesion.get("mask_path")
        if not key:
            continue
        grouped.setdefault(str(key), []).append(lesion)
    return grouped


class _LesionCentricSampler:
    """Internal iterator-producing sampler for one TorchIO subject."""

    def __init__(
        self,
        subject: tio.Subject,
        patch_size: Tuple[int, int, int],
        lesions: Sequence[Dict[str, Any]],
        sampling_profile: Dict[str, Any],
        mask_name: str,
        config: LesionSamplerConfig,
        stochastic: bool,
    ):
        self.subject = _ensure_min_size(subject, patch_size)
        self.patch_size = np.asarray(patch_size, dtype=np.int64)
        self.patch_size_tuple = tuple(int(v) for v in patch_size)
        self.mask_name = mask_name
        self.config = config
        self.stochastic = stochastic
        self.spatial_shape = np.asarray(self.subject.spatial_shape, dtype=np.int64)
        self.lesions = sorted(
            list(lesions),
            key=lambda row: (
                str(row.get("size_bin") or ""),
                -float(row.get("volume_vox") or 0),
                int(row.get("lesion_id") or 0),
            ),
        )
        self.sampling_profile = sampling_profile
        self.patch_budget_by_bin = dict(sampling_profile.get("suggested_patch_budget_by_size_bin", {}))
        self.role_priors_by_bin = dict(sampling_profile.get("suggested_patch_role_priors_by_size_bin", {}))
        self.empirical_probs = dict(sampling_profile.get("empirical_size_bin_probabilities", {}))
        self.target_probs = dict(sampling_profile.get("target_size_bin_probabilities", {}))
        self._selection_audit: Optional[Dict[str, Any]] = None
        self._planned_patches = self._plan_patches()

    def _rebalance_weight(self, size_bin: str) -> float:
        empirical = float(self.empirical_probs.get(size_bin, 0.0))
        target = float(self.target_probs.get(size_bin, empirical))
        if empirical <= 0.0:
            return 1.0
        return max(0.5, min(2.0, target / empirical))

    def _patch_budget_for_lesion(self, lesion: Dict[str, Any]) -> int:
        size_bin = str(lesion.get("size_bin") or "medium")
        base_budget = int(self.patch_budget_by_bin.get(size_bin, 3))
        scaled_budget = int(round(base_budget * self._rebalance_weight(size_bin)))
        budget = max(1, scaled_budget)

        if self.config.max_patches_per_lesion is not None:
            budget = min(budget, int(self.config.max_patches_per_lesion))
        return budget

    def _ordered_roles(self, size_bin: str) -> List[str]:
        priors = self.role_priors_by_bin.get(size_bin) or {"center": 0.5, "border": 0.3, "context": 0.2}
        roles = ["center", "border", "context"]
        return sorted(roles, key=lambda role: float(priors.get(role, 0.0)), reverse=True)

    def _sample_roles(self, size_bin: str, count: int) -> List[str]:
        priors = self.role_priors_by_bin.get(size_bin) or {"center": 0.5, "border": 0.3, "context": 0.2}
        roles = np.array(["center", "border", "context"], dtype=object)
        probs = np.array([float(priors.get(str(role), 0.0)) for role in roles], dtype=np.float64)
        if probs.sum() <= 0.0:
            probs = np.array([0.5, 0.3, 0.2], dtype=np.float64)
        probs = probs / probs.sum()

        if self.stochastic:
            return [str(role) for role in np.random.choice(roles, size=count, replace=True, p=probs)]

        ordered = self._ordered_roles(size_bin)
        return [ordered[i % len(ordered)] for i in range(count)]

    def _lesion_center(self, lesion: Dict[str, Any]) -> np.ndarray:
        return np.asarray(lesion.get("centroid_vox", [0.0, 0.0, 0.0]), dtype=np.float64)

    def _lesion_extent(self, lesion: Dict[str, Any]) -> np.ndarray:
        extent = np.asarray(lesion.get("bbox_size_vox", [1.0, 1.0, 1.0]), dtype=np.float64)
        return np.maximum(extent, 1.0)

    def _role_center(self, lesion: Dict[str, Any], role: str, patch_index: int) -> np.ndarray:
        center = self._lesion_center(lesion)
        extent = self._lesion_extent(lesion)

        if role == "center":
            if self.stochastic:
                jitter = np.random.normal(
                    loc=0.0,
                    scale=np.maximum(1.0, self.config.center_jitter_fraction * extent),
                    size=3,
                )
                return center + jitter
            return center

        axis = int(np.argmax(extent))
        shift = np.zeros(3, dtype=np.float64)

        if self.stochastic:
            sign = float(np.random.choice([-1.0, 1.0]))
        else:
            sign = -1.0 if patch_index % 2 == 0 else 1.0

        if role == "border":
            distance = max(self.config.min_shift_voxels, self.config.border_shift_fraction * float(extent[axis]))
        else:  # context
            distance = max(self.config.min_shift_voxels, self.config.context_shift_fraction * float(extent[axis]))

        shift[axis] = sign * distance
        return center + shift

    def _center_to_start(self, center: np.ndarray) -> np.ndarray:
        start = np.round(center - (self.patch_size.astype(np.float64) / 2.0)).astype(np.int64)
        max_start = np.maximum(self.spatial_shape - self.patch_size, 0)
        return np.clip(start, 0, max_start)

    def _crop(self, start: np.ndarray) -> tio.Subject:
        x0, y0, z0 = [int(v) for v in start]
        dx, dy, dz = [int(v) for v in self.patch_size]
        sx, sy, sz = [int(v) for v in self.spatial_shape]

        crop = tio.Crop((x0, sx - (x0 + dx), y0, sy - (y0 + dy), z0, sz - (z0 + dz)))
        return crop(self.subject)

    def _plan_patches(self) -> List[Tuple[np.ndarray, Dict[str, Any], str]]:
        planned: List[Tuple[np.ndarray, Dict[str, Any], str]] = []

        for lesion in self.lesions:
            size_bin = str(lesion.get("size_bin") or "medium")
            budget = self._patch_budget_for_lesion(lesion)
            roles = self._sample_roles(size_bin, budget)
            for patch_index, role in enumerate(roles):
                center = self._role_center(lesion, role, patch_index)
                start = self._center_to_start(center)
                planned.append((start, lesion, role))

        if not planned and float(self.config.background_sampling_prob) > 0.0:
            if self.stochastic:
                random_start = np.array(
                    [
                        np.random.randint(0, int(max(1, dim - patch + 1)))
                        for dim, patch in zip(self.spatial_shape.tolist(), self.patch_size.tolist())
                    ],
                    dtype=np.int64,
                )
            else:
                random_start = np.maximum((self.spatial_shape - self.patch_size) // 2, 0)
            planned.append((random_start, {"size_bin": "background", "lesion_id": -1}, "background"))

        if self.stochastic and planned:
            order = np.random.permutation(len(planned))
            planned = [planned[i] for i in order]

        if self.config.audit_enabled:
            self._selection_audit = {
                "num_lesions": len(self.lesions),
                "num_planned_patches": len(planned),
                "lesion_ids": [int(item[1].get("lesion_id", -1)) for item in planned],
                "roles": [str(item[2]) for item in planned],
            }
            logger.debug("Lesion-centric sampler audit: %s", self._selection_audit)

        return planned

    def __len__(self) -> int:
        return len(self._planned_patches)

    def __iter__(self) -> Iterator[tio.Subject]:
        for start, _lesion, _role in self._planned_patches:
            yield self._crop(start)


class LesionCentricSamplerWrapper(tio.data.sampler.PatchSampler):
    """Queue-compatible lesion-centric TorchIO sampler wrapper."""

    def __init__(
        self,
        patch_size: Tuple[int, int, int],
        lesion_catalog: Sequence[Dict[str, Any]],
        sampling_profile: Dict[str, Any],
        mask_name: str = "mask",
        config: Optional[LesionSamplerConfig] = None,
        stochastic: bool = True,
    ):
        super().__init__(patch_size)
        self.mask_name = mask_name
        self.config = config or LesionSamplerConfig()
        self.stochastic = stochastic
        self.sampling_profile = sampling_profile
        self.lesions_by_key = _group_lesions_by_catalog_key(lesion_catalog)

    def __call__(self, subject: tio.Subject) -> Iterable[tio.Subject]:
        subject_key_name = self.config.subject_key_name
        if subject_key_name not in subject:
            raise KeyError(
                f"Subject is missing required key '{subject_key_name}'. "
                "Attach a stable catalog key in the dataloader so the sampler can "
                "match subjects to lesion_catalog entries."
            )

        catalog_key = str(subject[subject_key_name])
        lesions = self.lesions_by_key.get(catalog_key, [])

        sampler = _LesionCentricSampler(
            subject=subject,
            patch_size=tuple(int(v) for v in self.patch_size.tolist()),  # type: ignore[arg-type]
            lesions=lesions,
            sampling_profile=self.sampling_profile,
            mask_name=self.mask_name,
            config=self.config,
            stochastic=self.stochastic,
        )
        return iter(sampler)


# Backward-compat alias to minimize external changes.
AdaptiveTumorSamplerWrapper = LesionCentricSamplerWrapper
